### ISSUE TITLE
arithmetic mod

### ISSUE THREAD

**Issue by askethi** [teyjus/teyjus#101]
Typing
R is 5 mod 2.
yields
(1,7): Error : operator is not a function
operator type: int
in expression: 5 mod 2.
In source\tables_gen\pervasives\pervasives.in there are following lines:

      /* int -> int */
      TYPE      7      int -> int
        /* unary minus on integers */
       56  %i~        intuminus  0 0  0  TRUE   FALSE  MAX PREFIX   NOCODE -
        /* modulus */
       61  mod        mod        0 0  0  TRUE   TRUE   160 INFIXL   NOCODE 

 Placing the last string in
TYPE 8   int -> int -> int
section below seems to work.

**Comment by fafounet** [comment]
Thanks for the report and the fix suggestion. It's now fixed in master.
