### ISSUE TITLE
teyjus will not compile on ubuntu 17.10

### ISSUE THREAD

**Issue by ggw10** [teyjus/teyjus#116]
tried to compile the 2.1 release on Ubuntu 17.19: the first non-warning error messages are
In file included from code.c:32:0:
code.c: In function ‘LoadCode’:
code.c:330:17: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘CodeInd {aka long int}’ [-Wformat=]
           debug("L:%d\t",*(CodeInd*)(code+j));
                 ^        ~~~~~~~~~~~~~~~~~~~
linker_message.h:27:58: note: in definition of macro ‘debug’
 #define debug(...) if(linker_verbosity>2){fprintf(stderr,__VA_ARGS__);}
                                                          ^~~~~~~~~~~
- build source/loader code.o                                                   
+ gcc -g -I. -c -o code.o code.c
In file included from code.c:32:0:
code.c: In function ‘LD_CODE_LoadCode’:
code.c:126:24: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long int’ [-Wformat=]
               LD_debug("L%x ",*(CSpacePtr*)(code+j)-codeSpaceBeg);
                        ^      ~~~~~~~~~~~~~~~~~~~~~~~
ld_message.h:27:58: note: in definition of macro ‘LD_debug’
 #define LD_debug(...) {if(LD_verbosity>2){fprintf(stderr,__VA_ARGS__);}}
                                                          ^~~~~~~~~~~

This seems to be a problem of non-reducibility of some complex type to int. 

stdout and stderr of compilation attached. 
[error.txt](https://github.com/teyjus/teyjus/files/1713810/error.txt)
[out.txt](https://github.com/teyjus/teyjus/files/1713811/out.txt)

**Comment by nguermond** [comment]
Build is now with dune, and Ubuntu 17 is no longer supported
