### ISSUE TITLE
Yeyjus does not build on Fedora 27

### ISSUE THREAD

**Issue by iaincraig** [teyjus/teyjus#118]
Error reads:
Error: No implementations provided for the following modules:
         Ccode_stubs referenced from front/module.cmx, front/readterm.cmx,
           front/query.cmx, front/front.cmx
*** omake: 1104/1123 targets are up to date                                    
*** omake: failed (4.29 sec, 154/154 scans, 173/225 rules, 543/1067 digests)
*** omake: targets were not rebuilt because of errors:                         
   source/tjsim.opt

**Comment by dtpeters** [comment]
Hey just wanted to add that I'm also getting this exact errror. I've tried blowing away the repo and using different ocaml versions via opam and I keep ending up here.

**Comment by gisellemnr** [comment]
The attached patch fixes this issue (based on the fix at https://github.com/teyjus/teyjus/issues/112#issuecomment-272336299).
Just remove the `.txt` extension to apply.


[0002-Renaming-ccode_stubs-for-compilation.patch.txt](https://github.com/teyjus/teyjus/files/3435821/0002-Renaming-ccode_stubs-for-compilation.patch.txt)
