### ISSUE TITLE
Compiling teyjus on windows

### ISSUE THREAD

**Issue by yvting** [teyjus/teyjus#120]
Hello teyjus developers,

I would like to know if there is a way to compile teyjus on windows for the moment. Specifically, I am asking if teyjus can be compiled in cygwin with opam installed.

Currently, I am using OCaml for Windows, installed by following the instruction on [https://fdopen.github.io/opam-repository-mingw/installation/](https://fdopen.github.io/opam-repository-mingw/installation/). After installed the packages teyjus depends on in cygwin. I ran 'omake' and got the following result:

```
Yuting Wang@DESKTOP-MEF52QE ~/Projects/teyjus
$ omake
*** omake: reading OMakefiles
--- Checking for ocamlfind... (found c:\cygwin64\home\yuting\.opam\ocaml-variants.4.11.1+mingw64c\bin\ocamlfind.exe)
--- Checking for ocamlc.opt... (found c:\cygwin64\home\yuting\.opam\ocaml-variants.4.11.1+mingw64c\bin\ocamlc.opt.exe)
--- Checking for ocamlopt.opt... (found c:\cygwin64\home\yuting\.opam\ocaml-variants.4.11.1+mingw64c\bin\ocamlopt.opt.exe)
--- Checking for ocamldep.opt... (found c:\cygwin64\home\yuting\.opam\ocaml-variants.4.11.1+mingw64c\bin\ocamldep.opt.exe)
--- Checking for ocamllex.opt... (found c:\cygwin64\home\yuting\.opam\ocaml-variants.4.11.1+mingw64c\bin\ocamllex.opt.exe)
--- Checking whether ocamlc understands the "z" warnings... (yes)
--- Checking whether ocamlopt can create cmxs plugins... (yes)
--- Checking if ocamldep understands -modules... (yes)
*** omake error:
   File source\test\compiler_negative_tests\OMakefile: line 9, characters 22-54
   Spawning c:\cygwin64\home\yuting\Projects\teyjus\source\test\compiler_negative_tests\multiple_local_constants\run_test failed:
      omake_shell_sys_create_process: process creation failed: %1 is not a valid Win32 application.
```

I tried to modify the makefile to make the compilation go through. However, it seems a non-trivial task. Does anyone knows what should I do?

Best,
Yuting

**Comment by Artemish** [comment]
Hello Yuting,

I tried running Cygwin with Omake installed, and was able to get past the run-tests line by changing `$(shell-code ./run_test $(FILE))` to `$(shell-code bash -c ./run_test $(FILE))` in this OMakefile, but had compilation issues after that, since I didn't have a i686-mingw gcc installed. If you're running Windows 10, I suggest using the Ubuntu [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) image and using OPAM to run with OCaml 4.02.1, which let Teyjus compile and run just fine.

**Comment by yvting** [comment]
OK. I have installed WSL2 and the problem is solved.
Still I would like to get teyjus working natively on windows. 
Also, I believe omake is kind of outdated. Hope the developers could switch to a more up-to-date build system like dune.
