### ISSUE TITLE
foreign function interface and code from Duanyang Jing

### ISSUE THREAD

**Issue by Xenate** [teyjus/teyjus#121]
I am trying use teyjus but without a foreign function interface it is lacking in usefulness to me. I found this paper: https://arxiv.org/pdf/1906.03970.pdf that outlines a method the modify teyjus and allow for a foreign function interface but I cannot find the modified compiler and I cannot figure out how to contact them because I am not an academic. I did find a forked teyjus repository under a Github account that I believe belongs to Duanyang Jing, but it seems to have never been committed to... If anybody has access to Jing, can help me find the code, or has any information on a foreign function interface in teyjus it would be greatly appreciated.

**Comment by abenedic** [comment]
Check the C interface branch of his code. I was just reading his paper and saw your comment: https://github.com/duanyangjing/teyjus/tree/C-interface
