### ISSUE TITLE
Adding syntax for rearrangeable predicate conditions.

### ISSUE THREAD

**Issue by Ktedon** [teyjus/teyjus#124]
I wanted to get the communities opinion on an improvement idea I have. One of the big issue with prolog-based language is that it is usually very difficult for people reading code to tell if two predicate conditions can be swapped for performance improvements. To fix this I propose we replace the current conjunction syntax ',' with '&' for rearrangeable conditions and '&&' for non rearrangeable conditions. Similarly we could replace disjunction syntax ';' with '|' for rearrangeable conditions and '||' for non rearrangeable conditions. 

Any thoughts on this?

**Comment by ThatDaleMiller** [comment]
It seems a bit heavy to modify the language as you suggest.  First, it might be difficult then to use the (rather nice) symbols &, &&, |, and || elsewhere in the language.  Actually, in the Teyjus implementation of lambda Prolog, both | and & are already used for other purposes.  Second, it would be easy for you to declare new infix operators and to define them directly in lambda Prolog via higher-order Horn clauses.  For example, 
```
or P Q :- P.
or P Q :- Q.
```
You could then use different symbols for the two disjunctions and two conjunctions as a way to document the distinctions you have in mind.

**Comment by Ktedon** [comment]
Your completely right. I just find that when talking to people about prolog one of their biggest criticisms is the fact that you don't know if you can change the order of the conditions. While you could implement it like that I find that many don't. I see this as not only being a way to encourage programmers to help other readers but to also help the compiler in optimizations. Perhaps my syntax proposals were a bit crude and premature but I still do see value in something like this. Despite many academic logic programming languages none have had the pleasure of being adopted for real world usage besides prolog and soon maybe mercury. The unfortunate thing is that both these languages are absolutely abhorrent and can be improved significantly. Enter Lambda-Prolog: LambdaProlog, a simple, typed, and higher-order logic programming language has the capability to evolve into something that can put logic programming in a serious position much like haskell has for functional programming. But as of now Lambda-Prolog is a bit simplistic and I believe has the potential to be something far more powerful without too many changes. I don't know the goals for this project specifically but if the community behind this implementation is not interested in some larger feature changes I'd be happy to start working on my own implementation with: some forms of code encapsulation via namespaces and protocols. Inheritance and multiple inheritance via protocols, VM reflection, type variances, literal types, implicits, union types, intersection types, type lambdas, classes?, path-dependent types, match types, anti-givens, FFI, a solid standard library, variable-length arguments, multi-threading, etc. While this may seem like a lot. Besides classes and namespaces, the changes are mostly there to improve expressiveness and the power of types and of course I am open to suggestions. Let me know what the future of this implementation is so that I can judge the best course of action. 

Thanks!

**Comment by ThatDaleMiller** [comment]
Thanks for your comments and enthusiasm about &lambda;Prolog.

> LambdaProlog, a simple, typed, and higher-order logic programming language has the capability to evolve into something that can put logic programming in a serious position much like haskell has for functional programming. 

Such an evolution could still be a goal.  The development of lambda Prolog to date has mostly been focused on keeping it close to logic and keeping it, in some sense, declarative.  One of the impacts of &lambda;Prolog has been to provide a useful logic within other computer systems, such as in the theorem provers Abella and Coq (via the Coq-Elpi plugin).  There is also the Makam system that uses &lambda;Prolog as a meta-language.  (Find links to these systems  [here](http://www.lix.polytechnique.fr/~dale/lProlog/).)  Such a role of $lambda;Prolog as a useful logic system has been a goal of mine for a number of years.  Note that in these settings, high-performance implementations of &lambda;Prolog have not been a focus. 

I'm sure that one thing that stops &lambda;Prolog getting adopted by more programmers as a stand-alone programming language is its lack of features, such as those you mentioned.  I would suggest, however, that another reason is the lack of high-performance implementations.  The development of Haskell, for example, was certainly influenced a great deal by a lot of early work on compilation and abstract machines.  Further development of the Teyjus compiler and the Elpi interpreter (both are open-source) along the lines of performance might help with getting this language adopted by more people.

**Comment by Ktedon** [comment]
That is great to know. After thinking about some of the changes I put forward, I thought that they might be a bit heavy for such a system so I started writing my own compiler that can be found here: https://github.com/Ktedon/Kierkegaard_Language. I do want to keep it as declarative as possible and so I have been trying very carefully to design the language in such a manner as to allow for complete declarative and logic-based programming. For example, classes are essentially type declarations with predicates allowing for simplified variable passing within those predicates. I do plan on keeping things as declarative as possible at least. I found [this paper](https://link.springer.com/chapter/10.1007/BFb0052186) for example that defines a declarative notion of object oriented programming. I hope I can extends such notions to other features. The point I am trying to make is that it seems that for more features than initially expected can be extended to declarative and logic-based programming.

I would still like this language to be useful for theorem proving. I think one of the things we are seeing is longer and longer proofs some as long as a sizeable novel. Perhaps some more powerful features might help in expressing these problems. Note this language I am designing is very much based on lambda prolog. You can see it to lambda prolog is like what c++ is to c. That is, almost 100% backwards compatible.

I do agree that performance could be a reason for a lack of adoption but I also see that people are using python for production systems for whatever reason. Perhaps all that is required is a foreign function interface. Even historically we have seen the capability of lambda prolog to be used for more industrial things, for example, the [hocompiler](https://github.com/teyjus/teyjus/tree/master/source/test/system_tests/hocompiler) which I found to be a pleasant surprise.

I don't think we should underestimate the ability of general-purpose languages for theorem proving. Even python is being used for theorem proving as seen [here](https://arxiv.org/pdf/1905.05970.pdf). Haha.

Thanks for the responses, 
Ktedon.
