### ISSUE TITLE
Unification fails on MacOS

### ISSUE THREAD

**Issue by vilhelms** [teyjus/teyjus#99]
Sorry for the vagueness of this bug report, but I figured I should at least mention that there is an issue. 

On my macbook, Mac OS 10.8.5, ocaml 4.01.0, teyjus builds without any error, and superficially appears to work, but higher-order unification sometimes fails to return solutions. E.g. in the pcf example, I get

    ~/builds/teyjus/examples/pcf$ ../../tjsim poly_test.lp
    Welcome to Teyjus
    Copyright (C) 2008 A. Gacek, S. Holte, G. Nadathur, X. Qi, Z. Snow
    Teyjus comes with ABSOLUTELY NO WARRANTY
    This is free software, and you are welcome to redistribute it
    under certain conditions. Please view the accompanying file
    COPYING for more information
    [poly_test] ?- poly_test "fib" T.

    no (more) solutions

    [poly_test] ?- 

Building on my linux desktop machine (also using ocaml 4.01.0) works correctly as expected. 

I see this with the latest git version (469c04ea87502625dee6aa7c068cf06f37b0878a) and also with an older version that I downloaded from Google Code in August 2013, so I guess this has been broken for a while.

(Incidentally, since I don't know lambda-Prolog it took me a while to convince myself that the implementation was broken rather than me doing something wrong. It might be a good idea to add some kind of tests to the distribution, to check that the build worked correctly).

**Comment by fafounet** [comment]
Hi!

Thanks for reporting the bug. Could you tell us the result of running omake test in the source directory?

You are absolutely right that we should have a way to test Teyjus on different OS.

Dale, could you create a project on https://ci.inria.fr so we have an automated way to test Teyjus on different systems. Could you then add me to the project (user: fafounet@gmail.com).
Maybe Giselle could figure out if there is someone in the lab who could get a Mac OS iso (in a legal way) to run it on ci.inria.fr. Some information here: http://apple.stackexchange.com/questions/145178/where-may-i-legally-get-a-mac-os-x-iso-file-to-virtualize-os-x

Thanks!

I can play a bit with the setup afterwards.


Fabien

**Comment by vilhelms** [comment]
Running omake test also fails a lot on my machine:

    *** omake: reading OMakefiles
    *** omake: finished reading OMakefiles (0.16 sec)
    - build source/test/system_tests <system-test>
    + perl harness
    append/append.t ..................... 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/6 subtests 
    assoc/assoc.t ....................... 
    Dubious, test returned 3 (wstat 768, 0x300)
    Failed 3/3 subtests 
    church/church.t ..................... 
    Dubious, test returned 8 (wstat 2048, 0x800)
    Failed 8/9 subtests 
    exportdef/exportdef.t ............... 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/1 subtests 
    funs/funs.t ......................... 
    Dubious, test returned 3 (wstat 768, 0x300)
    Failed 3/7 subtests 
    handbook_logic_hcinterp/hcinterp.t .. 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/1 subtests 
    handbook_logic_hcsyntax/hcsyntax.t .. 
    Dubious, test returned 5 (wstat 1280, 0x500)
    Failed 5/8 subtests 
    handbook_logic_pnf/pnf.t ............ 
    Dubious, test returned 4 (wstat 1024, 0x400)
    Failed 4/4 subtests 
    handbook_progs_curry/curry.t ........ 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/1 subtests 
    handbook_progs_eval/eval.t .......... 
    Dubious, test returned 12 (wstat 3072, 0xc00)
    Failed 12/12 subtests 
    handbook_progs_tr1/tr1.t ............ 
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/3 subtests 
    handbook_progs_tr2/tr2.t ............ 
    Dubious, test returned 3 (wstat 768, 0x300)
    Failed 3/4 subtests 
    hilbert/hilbert.t ................... ok
    hocompiler/comp.t ................... 
    Dubious, test returned 5 (wstat 1280, 0x500)
    Failed 5/5 subtests 
    lists/lists.t ....................... 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/9 subtests 
    maps/maps.t ......................... 
    Dubious, test returned 7 (wstat 1792, 0x700)
    Failed 7/11 subtests 
    pcf_eval/pcf_eval.t ................. 
    Dubious, test returned 5 (wstat 1280, 0x500)
    Failed 5/5 subtests 
    pcf_mono/pcf_mono.t ................. 
    Dubious, test returned 16 (wstat 4096, 0x1000)
    Failed 16/19 subtests 
    pcf_poly/pcf_poly.t ................. 
    Dubious, test returned 16 (wstat 4096, 0x1000)
    Failed 16/19 subtests 
    pcf_tr/tr.t ......................... 
    Dubious, test returned 6 (wstat 1536, 0x600)
    Failed 6/9 subtests 
    poplmark-3/poplmark-3.t ............. ok
    reverse/reverse.t ................... 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/2 subtests 
    SKI/combos2.t ....................... 
    Dubious, test returned 5 (wstat 1280, 0x500)
    Failed 5/5 subtests 
    typeinf/mlt.t ....................... 
    Dubious, test returned 16 (wstat 4096, 0x1000)
    Failed 16/23 subtests 

    Test Summary Report
    -------------------
    append/append.t                   (Wstat: 256 Tests: 6 Failed: 1)
      Failed test:  3
      Non-zero exit status: 1
    assoc/assoc.t                     (Wstat: 768 Tests: 3 Failed: 3)
      Failed tests:  1-3
      Non-zero exit status: 3
    church/church.t                   (Wstat: 2048 Tests: 9 Failed: 8)
      Failed tests:  1-8
      Non-zero exit status: 8
    exportdef/exportdef.t             (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    funs/funs.t                       (Wstat: 768 Tests: 7 Failed: 3)
      Failed tests:  1-3
      Non-zero exit status: 3
    handbook_logic_hcinterp/hcinterp.t (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    handbook_logic_hcsyntax/hcsyntax.t (Wstat: 1280 Tests: 8 Failed: 5)
      Failed tests:  1, 3, 5-7
      Non-zero exit status: 5
    handbook_logic_pnf/pnf.t          (Wstat: 1024 Tests: 4 Failed: 4)
      Failed tests:  1-4
      Non-zero exit status: 4
    handbook_progs_curry/curry.t      (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    handbook_progs_eval/eval.t        (Wstat: 3072 Tests: 12 Failed: 12)
      Failed tests:  1-12
      Non-zero exit status: 12
    handbook_progs_tr1/tr1.t          (Wstat: 512 Tests: 3 Failed: 2)
      Failed tests:  1-2
      Non-zero exit status: 2
    handbook_progs_tr2/tr2.t          (Wstat: 768 Tests: 4 Failed: 3)
      Failed tests:  1-2, 4
      Non-zero exit status: 3
    hocompiler/comp.t                 (Wstat: 1280 Tests: 5 Failed: 5)
      Failed tests:  1-5
      Non-zero exit status: 5
    lists/lists.t                     (Wstat: 256 Tests: 9 Failed: 1)
      Failed test:  3
      Non-zero exit status: 1
    maps/maps.t                       (Wstat: 1792 Tests: 11 Failed: 7)
      Failed tests:  1-3, 5-6, 8-9
      Non-zero exit status: 7
    pcf_eval/pcf_eval.t               (Wstat: 1280 Tests: 5 Failed: 5)
      Failed tests:  1-5
      Non-zero exit status: 5
    pcf_mono/pcf_mono.t               (Wstat: 4096 Tests: 19 Failed: 16)
      Failed tests:  1-9, 13-19
      Non-zero exit status: 16
    pcf_poly/pcf_poly.t               (Wstat: 4096 Tests: 19 Failed: 16)
      Failed tests:  1-9, 13-19
      Non-zero exit status: 16
    pcf_tr/tr.t                       (Wstat: 1536 Tests: 9 Failed: 6)
      Failed tests:  1-3, 6-7, 9
      Non-zero exit status: 6
    reverse/reverse.t                 (Wstat: 256 Tests: 2 Failed: 1)
      Failed test:  2
      Non-zero exit status: 1
    SKI/combos2.t                     (Wstat: 1280 Tests: 5 Failed: 5)
      Failed tests:  1-5
      Non-zero exit status: 5
    typeinf/mlt.t                     (Wstat: 4096 Tests: 23 Failed: 16)
      Failed tests:  1-16
      Non-zero exit status: 16
    Files=24, Tests=185, 32 wallclock secs ( 0.14 usr  0.06 sys + 18.36 cusr 11.96 csys = 30.52 CPU)
    Result: FAIL
    *** omake: 1810/1821 targets are up to date
    *** omake: failed (33.74 sec, 0/152 scans, 107/671 rules, 0/2881 digests)

**Comment by fafounet** [comment]
Hi!

I'm still investigating the issue. What kind of processor do you have?

Fabien

**Comment by vilhelms** [comment]
On 2015-07-05 18:28, fafounet wrote:
>
> Hi!
>
> I'm still investigating the issue. What kind of processor do you have?
>
> Fabien
>

1.8 GHz Intel Core i5.

$ file tjsim
tjsim: Mach-O 64-bit executable x86_64

**Comment by fafounet** [comment]
Thanks!

Could you try with the binary version from this page (version 2.1): https://github.com/teyjus/teyjus/releases

**Comment by vilhelms** [comment]
(Sorry for the delayed response---POPL deadline. :) )

Yes, it seems the binaries you linked to work on my machine! If I run 'perl harness' in the system_tests directory I only get a single error (exportdef/exportdef.t Failed test (../lib/Test/More.pm at line 349) got: '' #expected: 'X = 1'), while if I use the binaries that I build myself, I get hundreds of errors.

So, did you change anything, or are those built from the same source and by build environment is broken somehow?

**Comment by fafounet** [comment]
Hi!

I just compiled the sources in the only MacOS environment I can access:
- MacOS X 10.9.5
- ocaml 4.02.1
- OMake 0.9.8.6
- perl v5.16.2

Concerning the only failure: by mistake the binaries matched the commit before v2.1 where this particular test failed (known issue). I updated them on the release page but as the only difference is to ignore failure you don't have to do update.

I don't have time to investigate which particular thing is broken.

Could you confirm that ../../tjsim poly_test.lp know works as expected?
